 const ProjectData =[
    {
      "branch": "Information Technology Engineering",
      "appLink": "www.itaapp2.com",
      "description": "Building a blockchain-based supply chain management system for transparent and traceable logistics.",
      "documentation": "https://github.com/itauser/blockchain-scm/wiki",
      "domain": "Supply Chain",
      "features": ["Smart Contracts", "Real-time Tracking", "Supplier Authentication"],
      "github": "https://github.com/itauser/blockchain-scm",
      "goals": "Enhance transparency and efficiency in the supply chain",
      "process": "Blockchain development with periodic audits",
      "projectName": "SupplyChainBlock",
      "skillsUsed": ["Blockchain Development", "Smart Contracts", "Supply Chain Management"],
      "submittedOn": "28-Sep-2024",
      "userId": "itauser777"
    },
    {
      "branch": "Artificial Intelligence",
      "appLink": "www.aiapp3.com",
      "description": "Creating an AI-powered virtual assistant for automating administrative tasks and scheduling.",
      "documentation": "https://github.com/aiuser/virtual-assistant/wiki",
      "domain": "Automation",
      "features": ["Natural Language Processing", "Task Automation", "Calendar Integration"],
      "github": "https://github.com/aiuser/virtual-assistant",
      "goals": "Improve productivity through automated task management",
      "process": "Agile development with user feedback loops",
      "projectName": "AIVirtualAssistant",
      "skillsUsed": ["Natural Language Processing", "Machine Learning", "Task Automation"],
      "submittedOn": "15-Oct-2024",
      "userId": "aiuser888"
    },
    {
      "branch": "Electrical Engineering",
      "appLink": "www.eeapp3.com",
      "description": "Developing a smart grid system for efficient energy distribution and demand response in urban areas.",
      "documentation": "https://github.com/eeuser/smart-grid/wiki",
      "domain": "Smart Grids",
      "features": ["Demand Response", "Grid Optimization", "Renewable Energy Integration"],
      "github": "https://github.com/eeuser/smart-grid",
      "goals": "Optimize energy distribution and reduce peak load",
      "process": "Iterative development with grid simulations",
      "projectName": "SmartGridCity",
      "skillsUsed": ["Power Systems", "Renewable Energy", "Smart Grid Technologies"],
      "submittedOn": "01-Nov-2024",
      "userId": "eeuser678"
    },
    {
      "branch": "Computer Science Engineering",
      "appLink": "www.csapp3.com",
      "description": "Designing an e-learning platform with personalized course recommendations based on individual learning patterns.",
      "documentation": "https://github.com/csuser/e-learning-platform/wiki",
      "domain": "Education Technology",
      "features": ["Personalized Learning Paths", "Interactive Assessments", "Progress Tracking"],
      "github": "https://github.com/csuser/e-learning-platform",
      "goals": "Enhance personalized learning experiences for users",
      "process": "Continuous integration with frequent content updates",
      "projectName": "LearnSmart",
      "skillsUsed": ["Web Development", "Machine Learning", "Educational Technology"],
      "submittedOn": "15-Nov-2024",
      "userId": "csuser123"
    },
    {
      "branch": "Mechanical Engineering",
      "appLink": "www.meapp2.com",
      "description": "Developing a wearable exoskeleton to assist individuals with mobility impairments in daily activities.",
      "documentation": "https://github.com/meuser/exoskeleton/wiki",
      "domain": "Assistive Technology",
      "features": ["Mobility Assistance", "User Comfort Design", "Sensors for Adaptive Control"],
      "github": "https://github.com/meuser/exoskeleton",
      "goals": "Enhance mobility and independence for individuals with disabilities",
      "process": "User-centered design with iterative prototyping",
      "projectName": "MobilityAssist",
      "skillsUsed": ["Mechanical Design", "Biomechanics", "Sensor Integration"],
      "submittedOn": "22-Nov-2024",
      "userId": "meuser999"
    }
  
  ,
  
    {
      "branch": "Mechanical Engineering",
      "appLink": "www.meapp1.com",
      "description": "Developing an automated robotic arm for industrial manufacturing processes to improve efficiency and precision.",
      "documentation": "https://github.com/meuser/robotic-arm/wiki",
      "domain": "Automation",
      "features": ["Pick and Place", "Quality Control", "Integration with PLC"],
      "github": "https://github.com/meuser/robotic-arm",
      "goals": "Optimize manufacturing processes and reduce manual labor",
      "process": "Iterative prototyping with simulation testing",
      "projectName": "AutoArm",
      "skillsUsed": ["Robotics", "PLC Programming", "Simulation Tools"],
      "submittedOn": "18-Jul-2024",
      "userId": "meuser444"
    },
    {
      "branch": "Artificial Intelligence",
      "appLink": "www.aiapp2.com",
      "description": "Implementing a recommendation system for personalized content delivery based on user preferences and behavior.",
      "documentation": "https://github.com/aiuser/recommendation-system/wiki",
      "domain": "Personalization",
      "features": ["User Profiling", "Content Filtering", "Behavior Analysis"],
      "github": "https://github.com/aiuser/recommendation-system",
      "goals": "Enhance user satisfaction through personalized recommendations",
      "process": "Agile development with A/B testing",
      "projectName": "SmartRec",
      "skillsUsed": ["Machine Learning", "Recommendation Algorithms", "Big Data"],
      "submittedOn": "02-Aug-2024",
      "userId": "aiuser555"
    },
    {
      "branch": "Civil Engineering",
      "appLink": "www.civilapp2.com",
      "description": "Creating a GIS-based system for urban planning to optimize land use and infrastructure development.",
      "documentation": "https://github.com/civiluser/urban-planning/wiki",
      "domain": "Urban Planning",
      "features": ["GIS Mapping", "Land Zoning Analysis", "Infrastructure Simulation"],
      "github": "https://github.com/civiluser/urban-planning",
      "goals": "Efficient urban development with sustainable infrastructure",
      "process": "Collaborative planning with stakeholders",
      "projectName": "UrbanGIS",
      "skillsUsed": ["GIS", "Urban Planning", "Collaborative Tools"],
      "submittedOn": "15-Aug-2024",
      "userId": "civiluser789"
    },
    {
      "branch": "Computer Science Engineering",
      "appLink": "www.csapp2.com",
      "description": "Designing a real-time traffic management system using IoT devices and data analytics to reduce congestion.",
      "documentation": "https://github.com/csuser/traffic-management/wiki",
      "domain": "Smart Cities",
      "features": ["Traffic Monitoring", "Smart Traffic Signals", "Predictive Analytics"],
      "github": "https://github.com/csuser/traffic-management",
      "goals": "Improve urban mobility and reduce traffic congestion",
      "process": "Data-driven decision-making with continuous monitoring",
      "projectName": "CityFlow",
      "skillsUsed": ["IoT", "Data Analytics", "Smart City Technologies"],
      "submittedOn": "29-Aug-2024",
      "userId": "csuser999"
    },
    {
      "branch": "Electrical Engineering",
      "appLink": "www.eeapp2.com",
      "description": "Developing a smart home automation system with voice recognition for seamless control of devices and appliances.",
      "documentation": "https://github.com/eeuser/home-automation/wiki",
      "domain": "Home Automation",
      "features": ["Voice Commands", "Energy Efficiency", "Security Integration"],
      "github": "https://github.com/eeuser/home-automation",
      "goals": "Enhance convenience and energy efficiency in home automation",
      "process": "User-centered design with usability testing",
      "projectName": "SmartHomeVoice",
      "skillsUsed": ["Embedded Systems", "Voice Recognition", "Home Automation Protocols"],
      "submittedOn": "12-Sep-2024",
      "userId": "eeuser567"
    }
  ]
  
  export default ProjectData;